// Package main generates cc-pool's exact daemon wire identity.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
)

const (
	protocolPath = "internal/daemon/protocol.go"
	outputPath   = "internal/daemon/wirebuild_gen.go"
)

func main() {
	check := flag.Bool("check", false, "verify generated identity")
	protocol := flag.String("protocol", protocolPath, "protocol source path")
	output := flag.String("output", outputPath, "generated identity path")
	flag.Parse()
	canonical, err := canonicalSchema(*protocol)
	if err != nil {
		panic(err)
	}
	digest := sha256.Sum256(canonical)
	wireBuild := "com.yasyf.cc-pool.control/" + hex.EncodeToString(digest[:]) + "/v1"
	generated, err := format.Source([]byte(fmt.Sprintf(`// Code generated by wirebuildgen; DO NOT EDIT.

package daemon

const WireBuild = %q
`, wireBuild)))
	if err != nil {
		panic(err)
	}
	if *check {
		current, err := os.ReadFile(*output)
		if err != nil {
			panic(err)
		}
		if !bytes.Equal(current, generated) {
			panic("daemon WireBuild is stale; run go run ./internal/daemon/wirebuildgen")
		}
		return
	}
	if err := os.WriteFile(*output, generated, 0o600); err != nil {
		panic(err)
	}
}

func canonicalSchema(path string) ([]byte, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, err
	}
	types := make(map[string]*ast.TypeSpec)
	for _, declaration := range file.Decls {
		group, ok := declaration.(*ast.GenDecl)
		if !ok || group.Tok != token.TYPE {
			continue
		}
		for _, raw := range group.Specs {
			spec := raw.(*ast.TypeSpec)
			types[spec.Name.Name] = spec
		}
	}
	reachable := make(map[string]bool)
	queue := []string{"Request", "Response", "HealthRequest", "HealthResponse"}
	for len(queue) > 0 {
		name := queue[0]
		queue = queue[1:]
		if reachable[name] {
			continue
		}
		spec, ok := types[name]
		if !ok {
			return nil, fmt.Errorf("wire schema root type %s is missing", name)
		}
		reachable[name] = true
		ast.Inspect(spec.Type, func(node ast.Node) bool {
			identifier, ok := node.(*ast.Ident)
			if ok && !reachable[identifier.Name] && types[identifier.Name] != nil {
				queue = append(queue, identifier.Name)
			}
			return true
		})
	}
	var entries []string
	for _, declaration := range file.Decls {
		group, ok := declaration.(*ast.GenDecl)
		if !ok || (group.Tok != token.TYPE && group.Tok != token.CONST) {
			continue
		}
		for _, raw := range group.Specs {
			switch spec := raw.(type) {
			case *ast.TypeSpec:
				if !reachable[spec.Name.Name] {
					continue
				}
				body, err := render(fset, spec.Type)
				if err != nil {
					return nil, err
				}
				entries = append(entries, "type "+spec.Name.Name+" "+body)
			case *ast.ValueSpec:
				for index, name := range spec.Names {
					if !wireConstant(name.Name, spec.Type, reachable) {
						continue
					}
					entry := "const " + name.Name
					if spec.Type != nil {
						body, err := render(fset, spec.Type)
						if err != nil {
							return nil, err
						}
						entry += " " + body
					}
					if index < len(spec.Values) {
						body, err := render(fset, spec.Values[index])
						if err != nil {
							return nil, err
						}
						entry += " = " + body
					}
					entries = append(entries, entry)
				}
			}
		}
	}
	sort.Strings(entries)
	return []byte("cc-pool-control-schema/v1\n" + strings.Join(entries, "\n") + "\n"), nil
}

func wireConstant(name string, constantType ast.Expr, reachable map[string]bool) bool {
	if name == "DaemonHealthSchema" {
		return true
	}
	if name == "WireBuild" || strings.HasSuffix(name, "RoleID") {
		return false
	}
	identifier, ok := constantType.(*ast.Ident)
	return ok && reachable[identifier.Name]
}

func render(fset *token.FileSet, node any) (string, error) {
	var output bytes.Buffer
	if err := format.Node(&output, fset, node); err != nil {
		return "", err
	}
	return output.String(), nil
}
