// Code generated by wirebuildgen; DO NOT EDIT.

package daemon

import "github.com/yasyf/daemonkit"

const RuntimeSchema daemonkit.Schema = "com.yasyf.cc-pool.control/6c756710415cead877c8412e216aa3fea4ef0b5cdaef53a8e2c2690f70744fac/v2"
