// Code generated by wirebuildgen; DO NOT EDIT.

package daemon

import "github.com/yasyf/daemonkit"

const RuntimeSchema daemonkit.Schema = "com.yasyf.cc-pool.control/c727c0633413001b186b670d506672d270a9f7d82b10efcc2422bace03bdeb5a/v2"
